[font]
size = 8.0

[font.bold]
family = "SauceCodeProNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "SauceCodeProNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "SauceCodeProNerdFontMono"
style = "Italic"

[font.normal]
family = "SauceCodeProNerdFontMono"
style = "Regular"

[keyboard]
bindings = [{ key = "n", mods = "Control | Shift", action = "CreateNewWindow" }]
