theme = "autumn"

[editor]
auto-save = true
bufferline = "multiple"
soft-wrap.enable = true
end-of-line-diagnostics = "hint"

[editor.terminal]
command = "bash"
args = ["-c"]

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[keys.normal]
C-g = ["search_selection", "global_search"]
C-l = ["kill_to_line_end", "insert_mode"]
C-h = ["kill_to_line_start", "insert_mode"]

[keys.normal.backspace]
r = ":sh cargo run"
t = ":sh cargo test"
d = ":sh tree -I target"
l = ":o ~/.config/helix/languages.toml"

[keys.insert]
j = { k = "normal_mode" }

[keys.select]
